CREATE TABLE IF NOT EXISTS logistics(
  id BIGINT PRIMARY KEY,
  logistic_type BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  stock INTEGER NULL,
  component TEXT NOT NULL,
  max_price BIGINT NOT NULL,
  price BIGINT NOT NULL,
  expired_date TIMESTAMP WITHOUT TIME ZONE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT Now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT Now() 
);
